### ISSUE TITLE
Crash on world gen

### ISSUE THREAD

**Issue by Gegy** [Ladysnake/Gens#1]
```
java.lang.NullPointerException: Exception ticking world
	at ladysnake.gens.world.ComponentGensPieces$StructureType.access$500(ComponentGensPieces.java:56)
	at ladysnake.gens.world.ComponentGensPieces$Feature.offsetToAverageGroundLevel(ComponentGensPieces.java:123)
	at ladysnake.gens.world.ComponentGensPieces$Feature.func_74875_a(ComponentGensPieces.java:143)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:94)
	at ladysnake.gens.world.MapGenVillageWrapper.func_175794_a(MapGenVillageWrapper.java:30)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:406)
```

**Comment by JamiesWhiteShirt** [comment]
Should be fixed in ~~1.1~~ 1.2.
